---
apiVersion: v1
kind: pod
metadata:
  name: shannu-pod
  labels:
    app: shannu-pod
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerport: 80
          protocol: TCP
    